/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Array AST Node type
* by the ASTNode.java.ftl template
*/
package org.parsers.json.ast;

public class Array extends BaseNode {
}


