/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for Delimiter Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.json.ast;

import org.parsers.json.JSONLexer;
import org.parsers.json.Token;


public class Delimiter extends Token {

    public Delimiter(TokenType type, JSONLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


