/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for StringLiteral Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.json.ast;

import org.parsers.json.JSONLexer;


public class StringLiteral extends Literal {

    public StringLiteral(TokenType type, JSONLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


