/* Generated by: CongoCC Parser Generator. Do not edit.
* Generated Code for WHITESPACE Token subclass
* by the ASTToken.java.ftl template
*/
package org.parsers.json.ast;

import org.parsers.json.JSONLexer;
import org.parsers.json.Token;


public class WHITESPACE extends Token {

    public WHITESPACE(TokenType type, JSONLexer tokenSource, int beginOffset, int endOffset) {
        super(type, tokenSource, beginOffset, endOffset);
    }

}


