/* Generated by: CongoCC Parser Generator. InvalidToken.java  */
package org.parsers.json;


/**
* Token subclass to represent lexically invalid input
*/
public class InvalidToken extends Token {

    public InvalidToken(JSONLexer tokenSource, int beginOffset, int endOffset) {
        super(TokenType.INVALID, tokenSource, beginOffset, endOffset);
    }

}


